language: node_js
node_js:
  - "stable"

env:
  global:
  - GH_REPO="makotot/makoto.github.io"
  - GIT_COMMITTER_NAME=makotot
  - GIT_COMMITTER_EMAIL=makoto.ttn@gmail.com
  - GIT_AUTHOR_NAME=makotot
  - GIT_AUTHOR_EMAIL=makoto.ttn@gmail.com
  - secure: PTyxrK1CH4ao/yLohzVbVohkryNYumyHHhf1Ej81AQNttexcat/RPSDK7lEbBi5MIrC2WhLDCWm8o9+KeqBKrnjQto1q4i3jB+K7zu5hV5clWrP2R4lcrNWVYaDLR3+6mta615LfP6VniR7bRVI0fG8/eZApx/yPI2iTP+kWVIs=

branches:
  only:
  - dev

before_script:
- npm install -g gulp

script:
- npm run build

after_success:
- "./deploy.sh"

