language: node_js
node_js:
  - "stable"

env:
  global:
  - GH_REPO="makotot/makotot.github.io"
  - GIT_COMMITTER_NAME=makotot
  - GIT_COMMITTER_EMAIL=makoto.ttn@gmail.com
  - GIT_AUTHOR_NAME=makotot
  - GIT_AUTHOR_EMAIL=makoto.ttn@gmail.com
  - secure: "e+ZsFY1yc1gZtgQHPUsB0/RGodvlNn0usHijvMeKGwYzOFbmKb5YlGsXfF626eVXRZ9qrqY/ha0x7dE2rWPAcUf+V4t0gM1r4hcOCxzbfE2kzENA/63tfZvvrUOVD7kwi8zX2In6hqTkvOBZE65sZUNoNZPATUs558BiKR8jdVM="

branches:
  only:
  - dev

before_script:
- npm install -g gulp

script:
- npm run build

after_success:
- "./deploy.sh"

