language: node_js
node_js:
  - "stable"

env:
  global:
  - GH_REPO="makotot/makoto.github.io"
  - GIT_COMMITTER_NAME=makotot
  - GIT_COMMITTER_EMAIL=makoto.ttn@gmail.com
  - GIT_AUTHOR_NAME=makotot
  - GIT_AUTHOR_EMAIL=makoto.ttn@gmail.com
  - secure: "myL7jXX6PZnnxOMIEn153S9ipPlxHu40nsICEqN+6nRKvD8Ren5GHnLXQrtkbPUmo0FjrSX8NYA3eB1uCn0fC5brAe2BGqHnHlEP5AizJJN4bu1hogEGNirW8yrxBxqNh7mSOUOJNwacHcgepWVuXOhEt58p5Un7Q4R0Qh1Y634="

branches:
  only:
  - dev

before_script:
- npm install -g gulp

script:
- npm run build

after_success:
- "./deploy.sh"

